/**
 * Small slices of `w3gjs`'s internal id → name tables, copied verbatim
 * (values only reformatted to strip the library's category prefixes) since
 * the package only exports its top-level `W3GReplay` class — `mappings.js`
 * is not part of its public `exports` map (checked in
 * `node_modules/w3gjs/package.json`). See `apps/overlay/src/replay/
 * __fixtures__/LICENSE-w3gjs.txt` for the MIT license this data is under.
 *
 * We only copy what `describeId` (`idMap.ts`) and the hero-training
 * detector (`parseReplay.ts`) actually need:
 *  - `UPGRADE_NAMES` / `ITEM_NAMES` — display names for research and item
 *    ids, used as a fallback when `ID_MAP` doesn't have a dedicated entry.
 *  - `ABILITY_TO_HERO` — ability id -> 4-char hero unit id, source data for
 *    `HERO_IDS` (every trainable hero's unit id).
 *  - `HERO_NAMES` — 4-char hero unit id -> display name, derived from the
 *    `"<Hero Name>:<Ability Name>"` strings in w3gjs's `heroAbilities`
 *    table (also not otherwise available: heroes don't have their own name
 *    table in w3gjs, only per-ability strings).
 */

const UPGRADE_NAMES_RAW: Record<string, string> = {
  Rhss: "p_Control Magic",
  Rhme: "p_Swords",
  Rhra: "p_Gunpowder",
  Rhar: "p_Plating",
  Rhla: "p_Armor",
  Rhac: "p_Masonry",
  Rhgb: "p_Flying Machine Bombs",
  Rhlh: "p_Lumber Harvesting",
  Rhde: "p_Defend",
  Rhan: "p_Animal War Training",
  Rhpt: "p_Priest Training",
  Rhst: "p_Sorceress Training",
  Rhri: "p_Long Rifles",
  Rhse: "p_Magic Sentry",
  Rhfl: "p_Flare",
  Rhhb: "p_Storm Hammers",
  Rhrt: "p_Barrage",
  Rhpm: "p_Backpack",
  Rhfc: "p_Flak Cannons",
  Rhfs: "p_Fragmentation Shards",
  Rhcd: "p_Cloud",
  Resm: "p_Strength of the Moon",
  Resw: "p_Strength of the Wild",
  Rema: "p_Moon Armor",
  Rerh: "p_Reinforced Hides",
  Reuv: "p_Ultravision",
  Renb: "p_Nature's Blessing",
  Reib: "p_Improved Bows",
  Remk: "p_Marksmanship",
  Resc: "p_Sentinel",
  Remg: "p_Upgrade Moon Glaive",
  Redt: "p_Druid of the Talon Training",
  Redc: "p_Druid of the Claw Training",
  Resi: "p_Abolish Magic",
  Reht: "p_Hippogryph Taming",
  Recb: "p_Corrosive Breath",
  Repb: "p_Vorpal Blades",
  Rers: "p_Resistant Skin",
  Rehs: "p_Hardened Skin",
  Reeb: "p_Mark of the Claw",
  Reec: "p_Mark of the Talon",
  Rews: "p_Well Spring",
  Repm: "p_Backpack",
  Roch: "p_Chaos",
  Rome: "p_Melee Weapons",
  Rora: "p_Ranged Weapons",
  Roar: "p_Armor",
  Rwdm: "p_War Drums Damage Increase",
  Ropg: "p_Pillage",
  Robs: "p_Berserker Strength",
  Rows: "p_Pulverize",
  Roen: "p_Ensnare",
  Rovs: "p_Envenomed Spears",
  Rowd: "p_Witch Doctor Training",
  Rost: "p_Shaman Training",
  Rosp: "p_Spiked Barricades",
  Rotr: "p_Troll Regeneration",
  Rolf: "p_Liquid Fire",
  Ropm: "p_Backpack",
  Rowt: "p_Spirit Walker Training",
  Robk: "p_Berserker Upgrade",
  Rorb: "p_Reinforced Defenses",
  Robf: "p_Burning Oil",
  Rusp: "p_Destroyer Form",
  Rume: "p_Unholy Strength",
  Rura: "p_Creature Attack",
  Ruar: "p_Unholy Armor",
  Rucr: "p_Creature Carapace",
  Ruac: "p_Cannibalize",
  Rugf: "p_Ghoul Frenzy",
  Ruwb: "p_Web",
  Rusf: "p_Stone Form",
  Rune: "p_Necromancer Training",
  Ruba: "p_Banshee Training",
  Rufb: "p_Freezing Breath",
  Rusl: "p_Skeletal Longevity",
  Rupc: "p_Disease Cloud",
  Rusm: "p_Skeletal Mastery",
  Rubu: "p_Burrow",
  Ruex: "p_Exhume Corpses",
  Rupm: "p_Backpack",
};

const ITEM_NAMES_RAW: Record<string, string> = {
  amrc: "i_Amulet of Recall",
  ankh: "i_Ankh of Reincarnation",
  belv: "i_Boots of Quel'Thalas +6",
  bgst: "i_Belt of Giant Strength +6",
  bspd: "i_Boots of Speed",
  ccmd: "i_Scepter of Mastery",
  ciri: "i_Robe of the Magi +6",
  ckng: "i_Crown of Kings +5",
  clsd: "i_Cloak of Shadows",
  crys: "i_Crystal Ball",
  desc: "i_Kelen's Dagger of Escape",
  gemt: "i_Gem of True Seeing",
  gobm: "i_Goblin Land Mines",
  gsou: "i_Soul Gem",
  guvi: "i_Glyph of Ultravision",
  gfor: "i_Glyph of Fortification",
  soul: "i_Soul",
  mdpb: "i_Medusa Pebble",
  rag1: "i_Slippers of Agility +3",
  rat3: "i_Claws of Attack +3",
  rin1: "i_Mantle of Intelligence +3",
  rde1: "i_Ring of Protection +2",
  rde2: "i_Ring of Protection +3",
  rde3: "i_Ring of Protection +4",
  rhth: "i_Khadgar's Gem of Health",
  rst1: "i_Gauntlets of Ogre Strength +3",
  ofir: "i_Orb of Fire",
  ofro: "i_Orb of Frost",
  olig: "i_Orb of Lightning",
  oli2: "i_Orb of Lightning",
  oven: "i_Orb of Venom",
  odef: "i_Orb of Darkness",
  ocor: "i_Orb of Corruption",
  pdiv: "i_Potion of Divinity",
  phea: "i_Potion of Healing",
  pghe: "i_Potion of Greater Healing",
  pinv: "i_Potion of Invisibility",
  pgin: "i_Potion of Greater Invisibility",
  pman: "i_Potion of Mana",
  pgma: "i_Potion of Greater Mana",
  pnvu: "i_Potion of Invulnerability",
  pnvl: "i_Potion of Lesser Invulnerability",
  pres: "i_Potion of Restoration",
  pspd: "i_Potion of Speed",
  rlif: "i_Ring of Regeneration",
  rwiz: "i_Sobi Mask",
  sfog: "i_Horn of the Clouds",
  shea: "i_Scroll of Healing",
  sman: "i_Scroll of Mana",
  spro: "i_Scroll of Protection",
  sres: "i_Scroll of Restoration",
  ssil: "i_Staff of Silence",
  stwp: "i_Scroll of Town Portal",
  tels: "i_Goblin Night Scope",
  tdex: "i_Tome of Agility",
  texp: "i_Tome of Experience",
  tint: "i_Tome of Intelligence",
  tkno: "i_Tome of Power",
  tstr: "i_Tome of Strength",
  ward: "i_Warsong Battle Drums",
  will: "i_Wand of Illusion",
  wneg: "i_Wand of Negation",
  rdis: "i_Rune of Dispel Magic",
  rwat: "i_Rune of the Watcher",
  fgrd: "i_Red Drake Egg",
  fgrg: "i_Stone Token",
  fgdg: "i_Demonic Figurine",
  fgfh: "i_Spiked Collar",
  fgsk: "i_Book of the Dead",
  engs: "i_Enchanted Gemstone",
  k3m1: "i_Mooncrystal",
  modt: "i_Mask of Death",
  sand: "i_Scroll of Animate Dead",
  srrc: "i_Scroll of Resurrection",
  sror: "i_Scroll of the Beast",
  infs: "i_Inferno Stone",
  shar: "i_Ice Shard",
  wild: "i_Amulet of the Wild",
  wswd: "i_Sentry Wards",
  whwd: "i_Healing Wards",
  wlsd: "i_Wand of Lightning Shield",
  wcyc: "i_Wand of the Wind",
  rnec: "i_Rod of Necromancy",
  pams: "i_Anti-magic Potion",
  clfm: "i_Cloak of Flames",
  evtl: "i_Talisman of Evasion",
  nspi: "i_Necklace of Spell Immunity",
  lhst: "i_The Lion Horn of Stormwind",
  kpin: "i_Khadgar's Pipe of Insight",
  sbch: "i_Scourge Bone Chimes",
  afac: "i_Alleria's Flute of Accuracy",
  ajen: "i_Ancient Janggo of Endurance",
  lgdh: "i_Legion Doom-Horn",
  hcun: "i_Hood of Cunning",
  mcou: "i_Medallion of Courage",
  hval: "i_Helm of Valor",
  cnob: "i_Circlet of Nobility",
  prvt: "i_Periapt of Vitality",
  tgxp: "i_Tome of Greater Experience",
  mnst: "i_Mana Stone",
  hlst: "i_Health Stone",
  tpow: "i_Tome of Knowledge",
  tst2: "i_Tome of Strength +2",
  tin2: "i_Tome of Intelligence +2",
  tdx2: "i_Tome of Agility +2",
  rde0: "i_Ring of Protection +1",
  rde4: "i_Ring of Protection +5",
  rat6: "i_Claws of Attack +6",
  rat9: "i_Claws of Attack +9",
  ratc: "i_Claws of Attack +12",
  ratf: "i_Claws of Attack +15",
  manh: "i_Manual of Health",
  pmna: "i_Pendant of Mana",
  penr: "i_Pendant of Energy",
  gcel: "i_Gloves of Haste",
  totw: "i_Talisman of the Wild",
  phlt: "i_Phat Lewt",
  gopr: "i_Glyph of Purification",
  ches: "i_Cheese",
  mlst: "i_Maul of Strength",
  rnsp: "i_Ring of Superiority",
  brag: "i_Bracer of Agility",
  sksh: "i_Skull Shield",
  vddl: "i_Voodoo Doll",
  sprn: "i_Spider Ring",
  tmmt: "i_Totem of Might",
  anfg: "i_Ancient Figurine",
  lnrn: "i_Lion's Ring",
  iwbr: "i_Ironwood Branch",
  jdrn: "i_Jade Ring",
  drph: "i_Druid Pouch",
  hslv: "i_Healing Salve",
  pclr: "i_Clarity Potion",
  plcl: "i_Lesser Clarity Potion",
  rej1: "i_Minor Replenishment Potion",
  rej2: "i_Lesser Replenishment Potion",
  rej3: "i_Replenishment Potion",
  rej4: "i_Greater Replenishment Potion",
  rej5: "i_Lesser Scroll of Replenishment ",
  rej6: "i_Greater Scroll of Replenishment ",
  sreg: "i_Scroll of Regeneration",
  gold: "i_Gold Coins",
  lmbr: "i_Bundle of Lumber",
  fgun: "i_Flare Gun",
  pomn: "i_Potion of Omniscience",
  gomn: "i_Glyph of Omniscience",
  wneu: "i_Wand of Neutralization",
  silk: "i_Spider Silk Broach",
  lure: "i_Monster Lure",
  skul: "i_Sacrificial Skull",
  moon: "i_Moonstone",
  brac: "i_Runed Bracers",
  vamp: "i_Vampiric Potion",
  woms: "i_Wand of Mana Stealing",
  tcas: "i_Tiny Castle",
  tgrh: "i_Tiny Great Hall",
  tsct: "i_Ivory Tower",
  wshs: "i_Wand of Shadowsight",
  tret: "i_Tome of Retraining",
  sneg: "i_Staff of Negation",
  stel: "i_Staff of Teleportation",
  spre: "i_Staff of Preservation",
  mcri: "i_Mechanical Critter",
  spsh: "i_Amulet of Spell Shield",
  sbok: "i_Spell Book",
  ssan: "i_Staff of Sanctuary",
  shas: "i_Scroll of Speed",
  dust: "i_Dust of Appearance",
  oslo: "i_Orb of Slow",
  dsum: "i_Diamond of Summoning",
  fwss: "i_Frost Wyrm Skull Shield",
  ram1: "i_Ring of the Archmagi",
  ram2: "i_Ring of the Archmagi",
  ram3: "i_Ring of the Archmagi",
  ram4: "i_Ring of the Archmagi",
  shtm: "i_Shamanic Totem",
  shwd: "i_Shimmerweed",
  btst: "i_Battle Standard",
  skrt: "i_Skeletal Artifact",
  thle: "i_Thunder Lizard Egg",
  sclp: "i_Secret Level Powerup",
  gldo: "i_Orb of Kil'jaeden",
  tbsm: "i_Tiny Blacksmith",
  tfar: "i_Tiny Farm",
  tlum: "i_Tiny Lumber Mill",
  tbar: "i_Tiny Barracks",
  tbak: "i_Tiny Altar of Kings",
  mgtk: "i_Magic Key Chain",
  stre: "i_Staff of Reanimation",
  horl: "i_Sacred Relic",
  hbth: "i_Helm of Battlethirst",
  blba: "i_Bladebane Armor",
  rugt: "i_Runed Gauntlets",
  frhg: "i_Firehand Gauntlets",
  gvsm: "i_Gloves of Spell Mastery",
  crdt: "i_Crown of the Deathlord",
  arsc: "i_Arcane Scroll",
  scul: "i_Scroll of the Unholy Legion",
  tmsc: "i_Tome of Sacrifices",
  dtsb: "i_Drek'thar's Spellbook",
  grsl: "i_Grimoire of Souls",
  arsh: "i_Arcanite Shield",
  shdt: "i_Shield of the Deathlord",
  shhn: "i_Shield of Honor",
  shen: "i_Enchanted Shield",
  thdm: "i_Thunderlizard Diamond",
  stpg: "i_Clockwork Penguin",
  shrs: "i_Shimmerglaze Roast",
  bfhr: "i_Bloodfeather's Heart",
  cosl: "i_Celestial Orb of Souls",
  shcw: "i_Shaman Claws",
  srbd: "i_Searing Blade",
  frgd: "i_Frostguard",
  envl: "i_Enchanted Vial",
  rump: "i_Rusty Mining Pick",
  mort: "i_Mogrin's Report",
  srtl: "i_Serathil",
  stwa: "i_Sturdy War Axe",
  klmm: "i_Killmaim",
  rots: "i_Scepter of the Sea",
  axas: "i_Ancestral Staff",
  mnsf: "i_Mindstaff",
  schl: "i_Scepter of Healing",
  asbl: "i_Assassin's Blade",
  kgal: "i_Keg of Ale",
  dphe: "i_Thunder Phoenix Egg",
  dkfw: "i_Keg of Thunderwater",
  dthb: "i_Thunderbloom Bulb",
};

const ABILITY_TO_HERO: Record<string, string> = {
  AHbz: "Hamg",
  AHwe: "Hamg",
  AHab: "Hamg",
  AHmt: "Hamg",
  AHtb: "Hmkg",
  AHtc: "Hmkg",
  AHbh: "Hmkg",
  AHav: "Hmkg",
  AHhb: "Hpal",
  AHds: "Hpal",
  AHad: "Hpal",
  AHre: "Hpal",
  AHdr: "Hblm",
  AHfs: "Hblm",
  AHbn: "Hblm",
  AHpx: "Hblm",
  AEmb: "Edem",
  AEim: "Edem",
  AEev: "Edem",
  AEme: "Edem",
  AEer: "Ekee",
  AEfn: "Ekee",
  AEah: "Ekee",
  AEtq: "Ekee",
  AEst: "Emoo",
  AHfa: "Emoo",
  AEar: "Emoo",
  AEsf: "Emoo",
  AEbl: "Ewar",
  AEfk: "Ewar",
  AEsh: "Ewar",
  AEsv: "Ewar",
  AOwk: "Obla",
  AOmi: "Obla",
  AOcr: "Obla",
  AOww: "Obla",
  AOcl: "Ofar",
  AOfs: "Ofar",
  AOsf: "Ofar",
  AOeq: "Ofar",
  AOsh: "Otch",
  AOae: "Otch",
  AOws: "Otch",
  AOre: "Otch",
  AOhw: "Oshd",
  AOhx: "Oshd",
  AOsw: "Oshd",
  AOvd: "Oshd",
  AUdc: "Udea",
  AUdp: "Udea",
  AUau: "Udea",
  AUan: "Udea",
  AUcs: "Udre",
  AUsl: "Udre",
  AUav: "Udre",
  AUin: "Udre",
  AUfn: "Ulic",
  AUfa: "Ulic",
  AUfu: "Ulic",
  AUdr: "Ulic",
  AUdd: "Ulic",
  AUim: "Ucrl",
  AUts: "Ucrl",
  AUcb: "Ucrl",
  AUls: "Ucrl",
  ANbf: "Npbm",
  ANdb: "Npbm",
  ANdh: "Npbm",
  ANef: "Npbm",
  ANdr: "Nbrn",
  ANsi: "Nbrn",
  ANba: "Nbrn",
  ANch: "Nbrn",
  ANms: "Nngs",
  ANfa: "Nngs",
  ANfl: "Nngs",
  ANto: "Nngs",
  ANrf: "Nplh",
  ANca: "Nplh",
  ANht: "Nplh",
  ANdo: "Nplh",
  ANsg: "Nbst",
  ANsq: "Nbst",
  ANsw: "Nbst",
  ANst: "Nbst",
  ANeg: "Ntin",
  ANcs: "Ntin",
  ANc1: "Ntin",
  ANc2: "Ntin",
  ANc3: "Ntin",
  ANsy: "Ntin",
  ANs1: "Ntin",
  ANs2: "Ntin",
  ANs3: "Ntin",
  ANrg: "Ntin",
  ANg1: "Ntin",
  ANg2: "Ntin",
  ANg3: "Ntin",
  ANic: "Nfir",
  ANia: "Nfir",
  ANso: "Nfir",
  ANlm: "Nfir",
  ANvc: "Nfir",
  ANhs: "Nalc",
  ANab: "Nalc",
  ANcr: "Nalc",
  ANtm: "Nalc",
  ANcp: "Npal",
  AHcr: "Npal",
  AHpa: "Npal",
  AHcl: "Npal",
};

const HERO_ABILITIES_RAW: Record<string, string> = {
  AHbz: "a_Archmage:Blizzard",
  AHtb: "a_Mountain King:Storm Bolt",
  AHhb: "a_Paladin:Holy Light",
  AHdr: "a_Blood Mage:Siphon Mana",
  AEmb: "a_Demon Hunter:Mana Burn",
  AEer: "a_Keeper of the Grove:Entangling Roots",
  AEst: "a_Priestess of the Moon:Scout",
  AEbl: "a_Warden:Blink",
  AOwk: "a_Blademaster:Wind Walk",
  AOcl: "a_Far Seer:Chain Lighting",
  AOsh: "a_Tauren Chieftain:Shockwave",
  AOhw: "a_Shadow Hunter:Healing Wave",
  AUdc: "a_Death Knight:Death Coil",
  AUcs: "a_Dreadlord:Carrion Swarm",
  AUfn: "a_Lich:Frost Nova",
  AUim: "a_Crypt Lord:Impale",
  ANbf: "a_Pandaren Brewmaster:Breath of Fire",
  ANdr: "a_Dark Ranger:Life Drain",
  ANms: "a_Naga Sea Witch:Mana Shield",
  ANrf: "a_Pit Lord:Rain of Fire",
  ANsg: "a_Beastmaster:Summon Bear",
  ANeg: "a_Goblin Tinker:Engineering Upgrade",
  ANic: "a_Firelord:Incinerate",
  ANhs: "a_Goblin Alchemist:Healing Spray",
  ANcp: "a_Forsaken Paladin:Righteous Fury",
};

/** Strips w3gjs's category prefix ("i_", "p_", "u_", "b_", "a_") off a
 *  mapped display name. */
function stripPrefix(raw: string): string {
  return raw.replace(/^[a-z]_/, "");
}

function stripped(table: Record<string, string>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [id, raw] of Object.entries(table)) out[id] = stripPrefix(raw);
  return out;
}

export const UPGRADE_NAMES: Record<string, string> = stripped(UPGRADE_NAMES_RAW);
export const ITEM_NAMES: Record<string, string> = stripped(ITEM_NAMES_RAW);

/** 4-char hero unit id -> display name, derived from one representative
 *  ability string per hero in `HERO_ABILITIES_RAW` (the part before the
 *  ":"). */
export const HERO_NAMES: Record<string, string> = (() => {
  const out: Record<string, string> = {};
  for (const [abilityId, heroId] of Object.entries(ABILITY_TO_HERO)) {
    if (out[heroId]) continue;
    const raw = HERO_ABILITIES_RAW[abilityId];
    if (raw) out[heroId] = stripPrefix(raw).split(":")[0];
  }
  return out;
})();

/** Every trainable hero's 4-char unit id (race heroes + neutral/tavern
 *  heroes) — used to recognise a "train hero" order in the raw command
 *  stream (see `parseReplay.ts`'s hero-training detector). */
export const HERO_IDS: ReadonlySet<string> = new Set(Object.values(ABILITY_TO_HERO));

/** Replicates `w3gjs`'s internal `objectIdFormatter` (not exported):
 *  a 4-byte order id is "stringencoded" (a FourCC like "Ofar" or "hfoo")
 *  when its *last* byte is a printable letter (0x41-0x7a); otherwise it's
 *  a raw numeric order (move/attack/right-click/etc.) we don't care about
 *  here. Source: `node_modules/w3gjs/dist/esm/parsers/formatters.js`.
 *
 *  F001: numeric (non-FourCC) orders also carry a meaningful id — the
 *  Esc/Cancel-button order is the numeric id `0x0D0008`, verified against
 *  `w3c_6a87c0c1f214d632276e68be_shallow_grave.w3g` (a `0x10` action with
 *  raw bytes `[0x08, 0x00, 0x0D, 0x00]` at the moment skyplague's Mountain
 *  King order was cancelled). Unlike the FourCC branch's reversed-bytes
 *  decoding, numeric order ids are a plain little-endian `uint32` — this is
 *  always computed (even for FourCC ids, where it's unused) so callers
 *  never need to re-derive it. */
export function decodeOrderId(bytes: readonly number[]): { isFourCC: boolean; value: string; numeric: number } {
  const lastByte = bytes[3];
  const numeric = (bytes[0] ?? 0) | ((bytes[1] ?? 0) << 8) | ((bytes[2] ?? 0) << 16) | ((bytes[3] ?? 0) << 24);
  if (lastByte !== undefined && lastByte >= 0x41 && lastByte <= 0x7a) {
    const value = bytes
      .map((byte) => String.fromCharCode(byte))
      .reverse()
      .join("");
    return { isFourCC: true, value, numeric };
  }
  return { isFourCC: false, value: "", numeric };
}

/** The Esc/Cancel-button order — a `0x10` action whose order id decodes to
 *  this numeric value rather than a FourCC. See `decodeOrderId`'s docblock. */
export const ESC_CANCEL_ORDER_NUMERIC = 0x0d0008;
